Repository firehydrant/design-system, pull requests merged in 2021-09, with the labels that each got.

#108 fix(Button): adds 8px x-padding to tertiary variant
  lib/components/button/button.theme.js
Labels: enhancement, 🦄 ready for design review, ⚙️ ready for code review

#114 chore: remove unused package dependencies
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies, ⚙️ ready for code review

#105 feat(Menu): builds Menu component
  lib/components/menu/Menu.jsx
  lib/components/menu/Menu.stories.js
  lib/components/menu/MenuGroup.jsx
  lib/components/menu/MenuItem.jsx
  lib/components/menu/index.js
  lib/components/menu/menu.theme.js
  lib/main.js
  lib/theme/index.js
Labels: ready for code review

#125 chore(deps): bump Storybook from 6.3.6 to 6.3.8
  package-lock.json
  package.json
Labels: dependencies

#119 feat(ButtonDanger): adds Button Danger variant to Button
  lib/components/button/Button.stories.js
  lib/components/button/button.theme.js
Labels: ready for design review

#127 chore: update eslint config and add pre commit hooks
  .babelrc
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  CONTRIBUTING.md
  README.md
  lefthook.yml
  lib/components/alert/Alert.jsx
  lib/components/alert/Alert.stories.js
  lib/components/dropdown/Dropdown.stories.js
  lib/components/formlabel/formlabel.theme.js
  lib/components/menu/Menu.stories.js
  lib/components/table/table.theme.js
  package-lock.json
  package.json
Labels: ready for code review
